model:
  input_dim: 2048
  hidden_dims:  [128, 64]
  dropout: 0.6



train:
  epochs: 300
  batch_size: 64
  lr:  0.0001
  num_workers: 0
  weight_decay: 0.1

test:
  local_path: './check_point/molnet_rt_etkdgv3_tl.pt'
  github_release_url: 'https://github.com/JosieHong/3DMolMS/releases/download/v1.1.8/molnet_rt_etkdgv3_tl.zip'